site_name: Microwler
site_url: https://innovinati.github.io/microwler/
repo_url: https://github.com/INNOVINATI/microwler/
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Configuration: configuration.md
    - Scraping: scraping.md
    - Exporting: exporting.md
    - Web Service: webservice.md
    - FAQs: faq.md
theme: material
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
    watch:
      - ./microwler
extra_css:
    - css/termynal.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/INNOVINATI
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/innovinati

copyright: powered by <a href="https://innovinati.com/">INNOVINATI</a>
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences