site_name: Microwler
site_url: https://innovinati.github.io/microwler/
repo_url: https://github.com/INNOVINATI/microwler/
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Workflow: workflow.md
    - Configuration: configuration.md
    - Scraping: scraping.md
    - Exporting: exporting.md
    - JSON API: webservice.md
    - FAQs: faq.md
    - License: license.md
theme: material
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
    watch:
      - ./microwler
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/INNOVINATI/microwler
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/innovinati

copyright: powered by <a href="https://innovinati.com">INNOVINATI</a>
site_description: